version: '3.7' # specify docker-compose version
# Define the services/containers to be run
services:
  angular: # name of the first service
    hostname: localhost
    image: machgherl/gest-bibl-angular:0.1
    ports:
      - "8181:80" # specify port forwarding
  express: #name of the second service
    image: macgherl/gest-bibl-express:0.2
    ports:
      - "3000:3000" #specify ports forwarding
    depends_on:
      - database
  database: # name of the third service
    image: mysql:5.7 # specify image to build container from
    ports:
      - "3306:3306" # specify port forwarding
    environment:
      MYSQL_ROOT_PASSWORD: 'Hbn678%&00^'
    volumes:
      - "~/db_init:/docker-entrypoint-initdb.d"
